openapi: 3.0.0
info:
  title: Goodnight API
  version: 1.0.0
  description: A REST API for tracking sleep patterns and following friends' sleep records

servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login to get access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: alice
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

  /users/profile:
    get:
      tags:
        - Users
      summary: Get user profile with following/followers
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    $ref: '#/components/schemas/UserProfile'

  /follows/{userId}:
    post:
      tags:
        - Follows
      summary: Follow a user
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully followed user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
    delete:
      tags:
        - Follows
      summary: Unfollow a user
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully unfollowed user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /follows/sleep-records:
    get:
      tags:
        - Follows
      summary: Get friends' sleep records
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of friends' sleep records
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/FriendSleepRecord'

  /sleep/clock-in:
    post:
      tags:
        - Sleep
      summary: Start a sleep session
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully started sleep session
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    $ref: '#/components/schemas/SleepRecord'

  /sleep/clock-out:
    post:
      tags:
        - Sleep
      summary: End a sleep session
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully ended sleep session
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    $ref: '#/components/schemas/SleepRecord'

  /sleep/records:
    get:
      tags:
        - Sleep
      summary: Get user's sleep records
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of user's sleep records
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/SleepRecord'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        createdAt:
          type: string
          format: date-time
        following:
          type: array
          items:
            $ref: '#/components/schemas/UserBasic'
        followers:
          type: array
          items:
            $ref: '#/components/schemas/UserBasic'

    UserBasic:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string

    SuccessResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string

    FriendSleepRecord:
      type: object
      properties:
        id:
          type: integer
        clockIn:
          type: string
          format: date-time
        clockOut:
          type: string
          format: date-time
        duration:
          type: string
        user:
          type: object
          properties:
            username:
              type: string

    SleepRecord:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        clockIn:
          type: string
          format: date-time
        clockOut:
          type: string
          format: date-time
        duration:
          type: string
        durationFormatted:
          type: string
          example: "8h 30m"